#
# ~/.zshrc.d/10-history.zsh
#

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
